// A vendored, synchronous SHA-256 (FIPS 180-4), plus the UTF-8 encoder it is fed from.
//
// WHY this is not `crypto.subtle.digest` and not the platform hash module:
//
//   1. `@crr/core` is pure by contract, and a source-scanning test fails the build if a platform
//      module import appears anywhere in this directory. That contract is the architectural claim
//      of the whole project - the linker, the classifier and the digest are functions of their
//      arguments and nothing else - so the hash has to live inside the purity boundary, not punch
//      a hole through it.
//   2. `crypto.subtle.digest` is async. Making it the hash would make `digestOf` async, which
//      would make the linker async, which would make every one of the 28 link checks a promise.
//      A content address is a property of a document, not an I/O operation.
//   3. The digest is what an approval signature is taken over. It has to be computed identically
//      by the recorder, the linker, the replayer and a reviewer's script, on whatever runtime each
//      happens to be. One vendored implementation with published test vectors is a shorter path to
//      that than four platform APIs that agree until they do not.
//
// The cost is ~110 lines of well-understood code, pinned in test/sha256.test.ts to the published
// FIPS 180-4 vectors plus boundary vectors generated by an independent implementation.
//
// This is not a general-purpose crypto library. It hashes short canonical documents. It is not
// constant-time and must not be used for anything where that matters.

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

const rotr = (x: number, n: number): number => ((x >>> n) | (x << (32 - n))) >>> 0;

/** SHA-256 over raw bytes. Returns 64 lowercase hex characters. */
export function sha256Bytes(bytes: Uint8Array): string {
  const len = bytes.length;
  // The 64-bit big-endian bit length, split across two 32-bit words: (len * 8) is not
  // representable exactly as a 32-bit integer once len exceeds 2^29 bytes.
  const bitLenHi = Math.floor(len / 0x20000000) >>> 0;
  const bitLenLo = (len << 3) >>> 0;

  // Pad to a multiple of 64 bytes: 0x80, then zeros, then the 64-bit length.
  const padded = (((len + 9 + 63) / 64) | 0) * 64;
  const m = new Uint8Array(padded);
  m.set(bytes);
  m[len] = 0x80;
  const dv = new DataView(m.buffer);
  dv.setUint32(padded - 8, bitLenHi, false);
  dv.setUint32(padded - 4, bitLenLo, false);

  let h0 = 0x6a09e667;
  let h1 = 0xbb67ae85;
  let h2 = 0x3c6ef372;
  let h3 = 0xa54ff53a;
  let h4 = 0x510e527f;
  let h5 = 0x9b05688c;
  let h6 = 0x1f83d9ab;
  let h7 = 0x5be0cd19;

  const w = new Uint32Array(64);

  for (let off = 0; off < padded; off += 64) {
    for (let t = 0; t < 16; t++) w[t] = dv.getUint32(off + t * 4, false);
    for (let t = 16; t < 64; t++) {
      const x = w[t - 15] as number;
      const y = w[t - 2] as number;
      const s0 = (rotr(x, 7) ^ rotr(x, 18) ^ (x >>> 3)) >>> 0;
      const s1 = (rotr(y, 17) ^ rotr(y, 19) ^ (y >>> 10)) >>> 0;
      w[t] = ((w[t - 16] as number) + s0 + (w[t - 7] as number) + s1) >>> 0;
    }

    let a = h0;
    let b = h1;
    let c = h2;
    let d = h3;
    let e = h4;
    let f = h5;
    let g = h6;
    let h = h7;

    for (let t = 0; t < 64; t++) {
      const S1 = (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) >>> 0;
      const ch = ((e & f) ^ (~e & g)) >>> 0;
      const t1 = (h + S1 + ch + (K[t] as number) + (w[t] as number)) >>> 0;
      const S0 = (rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) >>> 0;
      const maj = ((a & b) ^ (a & c) ^ (b & c)) >>> 0;
      const t2 = (S0 + maj) >>> 0;
      h = g;
      g = f;
      f = e;
      e = (d + t1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) >>> 0;
    }

    h0 = (h0 + a) >>> 0;
    h1 = (h1 + b) >>> 0;
    h2 = (h2 + c) >>> 0;
    h3 = (h3 + d) >>> 0;
    h4 = (h4 + e) >>> 0;
    h5 = (h5 + f) >>> 0;
    h6 = (h6 + g) >>> 0;
    h7 = (h7 + h) >>> 0;
  }

  let hex = "";
  for (const v of [h0, h1, h2, h3, h4, h5, h6, h7]) hex += v.toString(16).padStart(8, "0");
  return hex;
}

/**
 * UTF-8 encode without `TextEncoder`.
 *
 * Hand-rolled so this package depends on no global beyond the ES2022 core objects. `TextEncoder`
 * is a WHATWG global rather than an ECMAScript one, so relying on it would make the type-level
 * story differ between DOM and platform lib configurations, for something that must behave
 * identically everywhere.
 *
 * Ill-formed input (a lone surrogate) becomes U+FFFD, matching `TextEncoder`. Note that this is a
 * lossy mapping: two different ill-formed strings can encode to the same bytes. That is why
 * `canonicalJson` refuses lone surrogates before they ever reach here - a canonicalizer that
 * silently merges two distinct values is a canonicalizer that merges two distinct digests.
 */
export function utf8(input: string): Uint8Array {
  const out: number[] = [];
  for (let i = 0; i < input.length; i++) {
    const c = input.charCodeAt(i);
    if (c < 0x80) {
      out.push(c);
    } else if (c < 0x800) {
      out.push(0xc0 | (c >> 6), 0x80 | (c & 0x3f));
    } else if (c >= 0xd800 && c <= 0xdbff) {
      const next = i + 1 < input.length ? input.charCodeAt(i + 1) : 0;
      if (next >= 0xdc00 && next <= 0xdfff) {
        const cp = 0x10000 + ((c - 0xd800) << 10) + (next - 0xdc00);
        out.push(
          0xf0 | (cp >> 18),
          0x80 | ((cp >> 12) & 0x3f),
          0x80 | ((cp >> 6) & 0x3f),
          0x80 | (cp & 0x3f),
        );
        i++;
      } else {
        out.push(0xef, 0xbf, 0xbd);
      }
    } else if (c >= 0xdc00 && c <= 0xdfff) {
      out.push(0xef, 0xbf, 0xbd);
    } else {
      out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 0x3f), 0x80 | (c & 0x3f));
    }
  }
  return new Uint8Array(out);
}

/** SHA-256 over a UTF-8 string. Returns 64 lowercase hex characters. */
export function sha256(input: string): string {
  return sha256Bytes(utf8(input));
}
