// `pnpm codegen` - the emitter, and the loop it closes.
//
// The interesting test is the last one in this file: generate a module from a contract, IMPORT IT,
// invoke with the `CAPABILITY` constant it exports, and get `ok` - then regenerate from a revised
// contract, invoke with the stale constant, and get `contract-stale`. That is the whole mechanism
// end to end, in one assertion, with the compiler's half proved next door in
// `test/typed-outcomes.test.ts`.

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { sealContract } from "@crr/core";
import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { main as codegenMain } from "../src/codegen-cli.js";
import {
  generateContractModule,
  generateIndexModule,
  identifierOf,
  moduleFileNameOf,
  writeGenerated,
} from "../src/codegen.js";
import { FileDocumentStore } from "../src/store.js";
import {
  DISCLOSURE_TRANSITIONS,
  disclosureArtifact,
  disclosureContract,
  disclosureScreens,
} from "./fixtures/disclosure.js";
import { host, invocation } from "./support/host.js";

const here = dirname(fileURLToPath(import.meta.url));
const scratch = resolve(here, "../.scratch");
const created: string[] = [];

function tmp(prefix: string): string {
  mkdirSync(scratch, { recursive: true });
  const dir = mkdtempSync(join(scratch, prefix));
  created.push(dir);
  return dir;
}

afterAll(() => {
  for (const dir of created) rmSync(dir, { recursive: true, force: true });
});

describe("naming", () => {
  it("keeps the capability's own spelling in the file name and camel-cases the identifier", () => {
    expect(moduleFileNameOf("corebank.member.read_share_position")).toBe(
      "corebank__member__read_share_position.ts",
    );
    expect(identifierOf("corebank.member.read_share_position")).toBe(
      "corebankMemberReadSharePosition",
    );
  });
});

describe("the emitted module", () => {
  const module = generateContractModule(disclosureContract);

  it("carries the digest as a runtime constant, which is the reason it is a .ts and not a .d.ts", () => {
    // A declaration file cannot hold a value, and `Invocation.capability.contractDigest` has to
    // travel on the wire. SPEC section 2.6 says `.d.ts`; this is the one place unit 12 corrects it.
    expect(module.source).toContain(
      `export const CONTRACT_DIGEST = ${JSON.stringify(disclosureContract.digest)}`,
    );
    expect(module.source).toContain("export const CAPABILITY");
  });

  it("preserves every outcome code as a literal, which is what makes the switch exhaustive", () => {
    expect(module.source).toContain('code: "MEMBER_NOT_FOUND"');
    expect(module.source).toContain('code: "MEMBER_RESTRICTED"');
    expect(module.source).toContain(
      'export type MockMemberDiscloseOutcome = "MEMBER_NOT_FOUND" | "MEMBER_RESTRICTED";',
    );
  });

  it("asserts the literal SATISFIES the contract rather than annotating it, which would widen it", () => {
    expect(module.source).toContain("as const satisfies CapabilityContract");
    expect(module.source).not.toContain(": CapabilityContract =");
  });

  it("says loudly that it is generated", () => {
    expect(module.source.startsWith("// GENERATED BY `pnpm codegen`. DO NOT EDIT.")).toBe(true);
  });

  it("is deterministic: the same contract emits byte-identical source", () => {
    expect(generateContractModule(disclosureContract).source).toBe(module.source);
    // ...including after a JSON round trip, because a store reads documents off disk.
    const roundTripped = JSON.parse(
      JSON.stringify(disclosureContract),
    ) as typeof disclosureContract;
    expect(generateContractModule(roundTripped).source).toBe(module.source);
  });

  it("emits a barrel that names every contract exactly once", () => {
    const index = generateIndexModule([disclosureContract]);
    expect(index.path).toBe("index.ts");
    expect(index.source).toContain(
      'export * as mockMemberDisclose from "./mock__member__disclose.js"',
    );
  });
});

describe("writing", () => {
  it("does not rewrite a file whose bytes already match", () => {
    const dir = tmp("codegen-");
    const first = writeGenerated([disclosureContract], dir);
    expect(first.written).toEqual(["mock__member__disclose.ts", "index.ts"]);
    expect(first.unchanged).toEqual([]);

    const second = writeGenerated([disclosureContract], dir);
    expect(second.written).toEqual([]);
    expect(second.unchanged).toEqual(["mock__member__disclose.ts", "index.ts"]);
  });
});

describe("the command", () => {
  // Captured rather than printed: the command is under test, and a suite that scrolls its own
  // output past the assertions is a suite nobody reads.
  let out = "";
  let err = "";
  beforeEach(() => {
    out = "";
    err = "";
    vi.spyOn(process.stdout, "write").mockImplementation((chunk) => {
      out += String(chunk);
      return true;
    });
    vi.spyOn(process.stderr, "write").mockImplementation((chunk) => {
      err += String(chunk);
      return true;
    });
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });

  function storeWith(contract = disclosureContract) {
    const dir = tmp("codegen-store-");
    new FileDocumentStore(dir).putContract(contract);
    return dir;
  }

  it("writes the modules a store's contracts describe", async () => {
    const store = storeWith();
    const outDir = join(tmp("codegen-out-"), "generated");
    expect(await codegenMain(["--store", store, "--out", outDir])).toBe(0);
    expect(existsSync(join(outDir, "mock__member__disclose.ts"))).toBe(true);
    expect(out).toContain("2 written, 0 unchanged");
  });

  it("passes --check when the generated files match, and fails when they do not", async () => {
    const store = storeWith();
    const outDir = join(tmp("codegen-out-"), "generated");
    expect(await codegenMain(["--store", store, "--out", outDir])).toBe(0);
    expect(await codegenMain(["--store", store, "--out", outDir, "--check"])).toBe(0);
    expect(out).toContain("codegen up to date");

    // Now the contract moves on and nobody regenerates. `--check` is the build-time half of the
    // digest pin, and it is the half that costs a caller nothing at run time.
    const revised = sealContract({ ...disclosureContract, summary: "Now says something else." });
    new FileDocumentStore(store).putContract(revised);
    expect(await codegenMain(["--store", store, "--out", outDir, "--check"])).toBe(1);
    expect(err).toContain("stale:");
  });

  it("reports rather than throws when a store holds no contracts", async () => {
    const empty = tmp("codegen-empty-");
    new FileDocumentStore(empty);
    expect(await codegenMain(["--store", empty, "--out", join(empty, "gen")])).toBe(1);
    expect(err).toContain("no contracts under");
  });
});

describe("the generated pin, used for real", () => {
  async function generateAndImport(contract: typeof disclosureContract) {
    const dir = tmp("codegen-live-");
    writeGenerated([contract], dir);
    const file = join(dir, moduleFileNameOf(contract.name));
    return (await import(pathToFileURL(file).href)) as {
      readonly CAPABILITY: {
        readonly name: string;
        readonly version: string;
        readonly contractDigest: string;
      };
      readonly CONTRACT_DIGEST: string;
    };
  }

  it("invokes ok when the generated module is current", async () => {
    const generated = await generateAndImport(disclosureContract);
    expect(generated.CONTRACT_DIGEST).toBe(disclosureContract.digest);

    const { catalog } = host({
      contract: disclosureContract,
      artifact: disclosureArtifact(),
      screens: disclosureScreens,
      transitions: DISCLOSURE_TRANSITIONS as never,
    });
    const result = await catalog.invoke(
      disclosureContract,
      invocation(disclosureContract, { memberId: "50001" }, { capability: generated.CAPABILITY }),
    );
    expect(result.status).toBe("ok");
  });

  it("invokes `contract-stale` when the generated module is a revision behind", async () => {
    // The caller regenerated against yesterday's contract; the host has today's.
    const yesterday = sealContract({
      ...disclosureContract,
      summary: "Reads three values about a member. (yesterday's wording)",
    });
    const generated = await generateAndImport(yesterday);
    expect(generated.CONTRACT_DIGEST).not.toBe(disclosureContract.digest);

    const { catalog, opens } = host({
      contract: disclosureContract,
      artifact: disclosureArtifact(),
      screens: disclosureScreens,
      transitions: DISCLOSURE_TRANSITIONS as never,
    });
    const result = await catalog.invoke(
      disclosureContract,
      invocation(disclosureContract, { memberId: "50001" }, { capability: generated.CAPABILITY }),
    );
    expect(result.status).toBe("failed");
    if (result.status !== "failed") return;
    expect(result.failure.class).toBe("contract-stale");
    expect(result.failure.sideEffects).toBe("none-guaranteed");
    expect(opens()).toBe(0);
  });

  it("never writes a contract's file content into the emitted module twice", () => {
    // A cheap guard against an emitter that concatenates instead of replacing.
    const dir = tmp("codegen-once-");
    writeGenerated([disclosureContract], dir);
    const source = readFileSync(join(dir, moduleFileNameOf(disclosureContract.name)), "utf8");
    const occurrences = source.split("export const mockMemberDisclose").length - 1;
    expect(occurrences).toBe(1);
  });
});
