// The discovery run that `@crr/runtime` replays. FINAL-STATUS section 7.2, closed.
//
// THE SEAM BETWEEN THE TWO HALVES OF SPEC SECTION 1.1 IS A FILE, AND THAT IS THE DESIGN RATHER THAN
// A WORKAROUND.
//
// `@crr/discovery` writes a capability; `@crr/runtime` executes one. Until now nothing in the
// workspace held both, so the cycle the whole submission is about - "the model discovers, the
// artifact becomes a reusable capability, deterministic replay is how the agent invokes it" - had
// never once been run end to end. The obvious fix is to make one package depend on the other. It is
// the wrong fix, and BRIEF section 3.9 says why in one line: THE ARTIFACT IS DATA, NOT CODE. A
// document that needs a function call to cross a package boundary is not a document. So synthesis
// emits `corebank-web.capability.json`, `packages/runtime/test/synthesized-replay.test.ts` reads it
// off disk the way a production catalog reads an artifact out of a store, and the seam between the
// half that writes the program and the half that executes it is exactly what the design says it is:
// a file, with a digest, that either parses or does not.
//
// WHAT IS REAL HERE AND WHAT IS NOT - read this before quoting anything from it.
//
//   REAL: the screens. `corebank-web.observations.json` is a frozen corpus of `Observation`s
//   captured from the REAL `fixtures/corebank-web` through the REAL `@crr/surface-browser` driver
//   over CDP `Accessibility.getFullAXTree` - 99, 130 and 159 nodes, the accessible names this
//   product actually computes (the search fields have none), the container paths its frameset
//   actually produces, and the `SurfaceCapabilities` that driver actually advertises. Every
//   descriptor synthesis derives below is derived from that, which is the whole reason the emitted
//   artifact can be executed against the live application rather than only against a mock.
//
//   REAL: the loop, the policy chokepoint, the projection, the tool schemas, synthesis. All of it
//   is the shipping code path.
//
//   NOT REAL: the model. `SCRIPT` is hand-authored - no provider was called, no token was spent,
//   BRIEF section 11 - so the run's provenance records `adapter: "replay"`, `modelId:
//   "synthetic-script"`, and this fixture MUST NEVER be presented as evidence of a discovery run.
//   That evidence comes from the `anthropic` adapter against the live API, in a run the author has
//   explicitly approved. See `evidence/discovery-live/PENDING.md`.
//
//   NOT REAL: the transitions between screens. A `MockSurface` moves between four frozen
//   observations on a declared script. The application's own responses to those actions were
//   observed once, at capture time, by `capture-corebank-web.ts` driving the real browser; what is
//   frozen here is the result of that observation, not a simulation of it.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type Allowlist,
  MOCK_LEASE_TOKEN,
  MockSurface,
  type MockTransition,
  type NodeId,
  type Observation,
  type SurfaceCapabilities,
  type Timestamp,
} from "@crr/core";
import {
  type DiscoveryRun,
  type ScriptedTurn,
  type SynthesisResult,
  type SynthesizeInput,
  createRecordingModel,
  createReplayModel,
  createScriptedModel,
  runDiscoveryLoop,
  synthesizeCapability,
} from "../../src/index.js";

// ---------------------------------------------------------------------------------------------
// The committed files
// ---------------------------------------------------------------------------------------------

const HERE = fileURLToPath(new URL(".", import.meta.url));

/** The frozen `Observation` corpus. Regenerated by `pnpm -F @crr/discovery fixtures:capture`,
 *  which needs a Chromium build; everything downstream of it is hermetic. */
export const OBSERVATIONS_FILE = "corebank-web.observations.json";

/** The emitted documents. Regenerated by `pnpm -F @crr/discovery fixtures:synthesized`, which needs
 *  nothing but this corpus - no browser, no clock, no credential. */
export const CAPABILITY_FILE = "corebank-web.capability.json";

export type ScreenName = "search" | "searchFilled" | "results" | "detail";

export interface CorebankWebCorpus {
  /** Said in the file itself, because a JSON document cannot carry a comment and this one will be
   *  read by somebody who did not open this module. */
  readonly _readme: string;
  readonly capture: {
    readonly driver: string;
    readonly fixture: string;
    readonly tenantId: string;
    readonly capturedAt: string;
    readonly command: string;
  };
  /** What the BROWSER driver advertises, not what a mock advertises. Synthesis refuses to record a
   *  descriptor kind the driver that will resolve it cannot resolve, so passing the real
   *  capabilities is the difference between a plausible artifact and an executable one. */
  readonly capabilities: SurfaceCapabilities;
  readonly screens: Readonly<Record<ScreenName, Observation>>;
}

export function loadCorpus(dir: string = HERE): CorebankWebCorpus {
  return JSON.parse(readFileSync(join(dir, OBSERVATIONS_FILE), "utf8")) as CorebankWebCorpus;
}

export interface EmittedCapability {
  readonly _readme: string;
  readonly provenance: {
    readonly emittedBy: string;
    readonly command: string;
    readonly corpus: string;
    readonly adapter: string;
    readonly modelId: string;
    readonly synthetic: true;
  };
  /** What the driver that recorded the run advertises. Carried WITH the documents so a consumer can
   *  run the linker's load-time refusal - "this surface cannot resolve a descriptor kind this
   *  program depends on" - without also having to hold the 280 KB observation corpus. */
  readonly capabilities: unknown;
  readonly contract: unknown;
  readonly artifact: unknown;
  readonly report: unknown;
}

export function loadEmitted(dir: string = HERE): EmittedCapability {
  return JSON.parse(readFileSync(join(dir, CAPABILITY_FILE), "utf8")) as EmittedCapability;
}

// ---------------------------------------------------------------------------------------------
// The run's inputs
// ---------------------------------------------------------------------------------------------

/** The member the recording was taken on. A FIXTURE member: five obviously synthetic digits that
 *  exist only in `fixtures/corebank-web/src/data.js`. It appears in the GOAL, which is what binds
 *  it to a parameter and keeps it out of every document synthesis emits. */
export const RECORDED_MEMBER_ID = "10041";

export const GOAL = [
  `Look up member ${RECORDED_MEMBER_ID} in the riverbend core banking back office,`,
  "report their name, share balance and membership status, and open their member record.",
].join(" ");

/**
 * Frozen. This module reads no clock, so a rebuild of the emitted documents is byte-identical and
 * the artifact's content address means something.
 */
export const FROZEN_NOW = "2026-02-14T10:00:00.000Z" as Timestamp;

/** A monotonic millisecond source with a fixed step: every call takes exactly one millisecond, so
 *  recorded latencies are reproducible and visibly synthetic. */
export function frozenClockMs(): () => number {
  let tick = 0;
  return () => {
    tick += 1;
    return tick;
  };
}

/**
 * What discovery is allowed to do, and it is NOT the deployment's replay allowlist.
 *
 * `WRITE_REVERSIBLE` because `defaultEffectOf` cannot prove that clicking a button labelled
 * "Search" is a read - SPEC section 8.2 is explicit that effect is DECLARED, not proven - and being
 * conservative in the safe direction is the whole point of that table. The consequence travels all
 * the way to the other end of this deliverable: the emitted artifact declares
 * `effects.maxEffect: "WRITE_REVERSIBLE"`, so the replay test's allowlist has to permit it too, and
 * that is a fact about synthesis worth seeing rather than tidying away.
 */
export const ALLOWLIST: Allowlist = {
  originAliases: ["corebank"],
  routes: [
    { originAlias: "corebank", pathPattern: "/search", maxEffect: "WRITE_REVERSIBLE" },
    { originAlias: "corebank", pathPattern: "/search/results", maxEffect: "WRITE_REVERSIBLE" },
    { originAlias: "corebank", pathPattern: "/member/:memberId", maxEffect: "WRITE_REVERSIBLE" },
  ],
  actionKinds: ["click", "type", "select", "setChecked", "pressKey", "focus", "navigate"],
  maxEffect: "WRITE_REVERSIBLE",
  discoveryMaxEffect: "WRITE_REVERSIBLE",
};

export const CONTROL = {
  token: MOCK_LEASE_TOKEN,
  snapshot: {
    holder: "automation",
    actorId: "run:corebank-web-discovery",
    epoch: 0,
    expiresAt: "2099-01-01T00:00:00.000Z",
  },
} as const;

export const ENTRY_ROUTE = "/search";

// ---------------------------------------------------------------------------------------------
// The node references, and the guard that keeps them honest
// ---------------------------------------------------------------------------------------------

/**
 * `n<k>` is an index into THAT TURN's `observation.nodes` (SPEC section 6.2), so a hand-authored
 * script is a set of integers with no names attached - and an integer that has quietly come to mean
 * a different control is the single worst way for this fixture to fail, because the run would still
 * complete and the artifact would still link.
 *
 * So every reference is checked against the corpus before the loop is started: the node at that
 * index must still have the role, and the accessible name, that the reference was chosen for. A
 * corpus recaptured after the fixture's markup moves fails HERE, naming both nodes, instead of
 * silently recording a program that clicks the Last Name field.
 *
 * `name: ""` is not a placeholder. This product's search inputs genuinely have no accessible name -
 * no `<label for>`, no `aria-label`, generated ids - which is why `role-name`, the descriptor you
 * would reach for first, is unusable on them and the quorum below is built from a label anchor and
 * an ordinal instead. Asserting the empty string is asserting the hostility.
 */
interface NodeRef {
  readonly screen: ScreenName;
  readonly index: number;
  readonly role: string;
  readonly name: string;
  readonly why: string;
}

export const REFS = {
  memberIdField: {
    screen: "search",
    index: 84,
    role: "textbox",
    name: "",
    why: "the first search input; this product gives it no accessible name at all",
  },
  searchButton: {
    // `searchFilled`, NOT `search`, and the difference is a measured property of this application
    // rather than bookkeeping. Typing into the member field makes Chromium materialise a
    // `StaticText` node for the value inside the field's layout cell, so the tree grows from 99
    // nodes to 100 and EVERY LATER INDEX SHIFTS BY ONE: the Search button is n97 before the fill
    // and n98 after it. A corpus that froze only the pre-fill screen would put the script one
    // index out of step with the live application, which is exactly the class of drift SPEC
    // section 6.2 makes node references single-turn to prevent. Both screens are captured.
    screen: "searchFilled",
    index: 98,
    role: "button",
    name: "Search",
    why: "the submit control on the search form, after the member number has been typed",
  },
  nameCell: {
    screen: "results",
    index: 121,
    role: "cell",
    name: "ALVAREZ, DANA (SYNTHETIC)",
    why: "the Name cell of the row whose Member ID column holds the number we searched for",
  },
  balanceCell: {
    screen: "results",
    index: 123,
    role: "cell",
    name: "1,204.55",
    why: "the Share Balance cell of that same row",
  },
  statusCell: {
    screen: "results",
    index: 125,
    role: "cell",
    name: "ACTIVE",
    why: "the Status cell of that same row",
  },
  openLink: {
    screen: "results",
    index: 128,
    role: "link",
    name: "Open",
    why: "the row action that opens the member's record",
  },
} as const satisfies Readonly<Record<string, NodeRef>>;

export class CorpusDriftError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CorpusDriftError";
  }
}

/** The node a reference points at, checked. Throws with both descriptions on any disagreement. */
export function nodeFor(corpus: CorebankWebCorpus, ref: NodeRef): NodeId {
  const screen = corpus.screens[ref.screen];
  const node = screen?.nodes[ref.index];
  if (node === undefined) {
    throw new CorpusDriftError(
      [
        `the corpus screen "${ref.screen}" has no node at index ${ref.index} (${ref.why});`,
        `it has ${screen?.nodes.length ?? 0}.`,
        "Recapture with `pnpm -F @crr/discovery fixtures:capture` and re-choose the references in REFS.",
      ].join(" "),
    );
  }
  if (node.ariaRole !== ref.role || node.name !== ref.name) {
    throw new CorpusDriftError(
      [
        `n${ref.index} on screen "${ref.screen}" was chosen as ${ref.role} "${ref.name}" (${ref.why})`,
        `and the corpus now has ${String(node.ariaRole)} "${node.name}" there.`,
        "The hand-authored script would act on the wrong control; re-choose the reference rather",
        "than adjusting the assertion.",
      ].join(" "),
    );
  }
  return node.id;
}

export function checkRefs(corpus: CorebankWebCorpus): void {
  for (const ref of Object.values(REFS)) nodeFor(corpus, ref);
}

// ---------------------------------------------------------------------------------------------
// The hand-authored model turns
// ---------------------------------------------------------------------------------------------

/**
 * One acting tool call per turn, which is the loop's own rule and not a stylistic choice: a
 * computer-use loop must observe the consequence of each action before choosing the next, or the
 * recorded step order means nothing.
 *
 * The three `note_output` calls are the model's entire contribution to the contract's outputs: a
 * node, a name and a sentence of meaning. It supplies no query, no parser, no type and no
 * sensitivity - `deriveOutputs` derives those from the frozen observation, which is why the
 * emitted `shareBalance` comes out `{ kind: "money", currency: "USD" }` rather than a string.
 */
export const SCRIPT: readonly ScriptedTurn[] = [
  {
    text: "Let me see the member search screen before I touch anything.",
    toolUses: [{ name: "observe", input: {} }],
  },
  {
    toolUses: [
      {
        name: "act",
        input: {
          nodeRef: `n${REFS.memberIdField.index}`,
          action: "fill",
          value: RECORDED_MEMBER_ID,
          key: null,
          why: `The task names member ${RECORDED_MEMBER_ID}, and this is the field beside the Member ID label.`,
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "act",
        input: {
          nodeRef: `n${REFS.searchButton.index}`,
          action: "activate",
          value: null,
          key: null,
          why: "Submit the search now that the member number is in the field.",
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "note_output",
        input: {
          nodeRef: `n${REFS.nameCell.index}`,
          outputName: "memberName",
          meaning: "The member's name as the core banking system holds it.",
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "note_output",
        input: {
          nodeRef: `n${REFS.balanceCell.index}`,
          outputName: "shareBalance",
          meaning: "The member's total share balance.",
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "note_output",
        input: {
          nodeRef: `n${REFS.statusCell.index}`,
          outputName: "accountStatus",
          meaning: "The membership's status on the core banking system.",
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "act",
        input: {
          nodeRef: `n${REFS.openLink.index}`,
          action: "activate",
          value: null,
          key: null,
          why: "Open the record of the member whose Member ID column matches the number I searched for.",
        },
      },
    ],
  },
  {
    toolUses: [
      {
        name: "finish",
        input: {
          status: "reached-goal",
          summary:
            "Entered the member number on the search form, read the member's name, share balance " +
            "and status off the matching row, and opened that member's record.",
          outcomeCandidates: null,
        },
      },
    ],
  },
];

// ---------------------------------------------------------------------------------------------
// The run
// ---------------------------------------------------------------------------------------------

/**
 * The declared moves between the three frozen screens.
 *
 * Written against node IDS read out of the corpus rather than typed in, so a recapture cannot leave
 * a transition pointing at a node that no longer exists - `MockSurface` would then throw
 * `no transition for {...}` several frames away from the cause.
 */
export function transitionsFor(corpus: CorebankWebCorpus): readonly MockTransition[] {
  return [
    // Typing does not NAVIGATE, but on this application it does change the tree - see
    // `REFS.searchButton`. So the fill moves the mock to the screen the browser really produced,
    // rather than staying put and letting `MockSurface` patch a value into the old one; a corpus
    // that modelled the fill as a pure value change would be modelling a different application.
    {
      from: "search",
      on: { kind: "type", target: nodeFor(corpus, REFS.memberIdField) },
      to: "searchFilled",
    },
    {
      from: "searchFilled",
      on: { kind: "click", target: nodeFor(corpus, REFS.searchButton) },
      to: "results",
    },
    {
      from: "results",
      on: { kind: "click", target: nodeFor(corpus, REFS.openLink) },
      to: "detail",
    },
  ];
}

export function surfaceFor(corpus: CorebankWebCorpus): MockSurface {
  return new MockSurface({
    screens: corpus.screens,
    start: "search",
    transitions: transitionsFor(corpus),
  });
}

export interface RunOptions {
  /** Supplied by the capture script, which drives the REAL browser instead of the corpus. */
  readonly surface?: MockSurface | Parameters<typeof runDiscoveryLoop>[0]["surface"];
  readonly model: Parameters<typeof runDiscoveryLoop>[0]["model"];
}

export async function runOver(options: RunOptions): Promise<DiscoveryRun> {
  return runDiscoveryLoop({
    goal: GOAL,
    target: { tenantId: "riverbend", originAlias: "corebank", entryRoute: ENTRY_ROUTE },
    model: options.model,
    surface: options.surface as Parameters<typeof runDiscoveryLoop>[0]["surface"],
    allowlist: ALLOWLIST,
    control: CONTROL,
    now: () => FROZEN_NOW,
    nowMs: frozenClockMs(),
  });
}

/**
 * The recorded run, replayed through the VCR so its provenance is honest.
 *
 * The scripted model is recorded to a transcript and the transcript is then REPLAYED to produce the
 * run synthesis actually consumes. That is not ceremony. `DISCOVERY_ADAPTERS` carries a fifth
 * member, `scripted`, that `@crr/core`'s `ProvenanceSchema` deliberately does not - synthesis
 * refuses to name an adapter in an artifact that no replay engine could have been driven by - so a
 * run taken straight off the scripted model cannot be sealed into an artifact at all. Going through
 * the VCR yields `adapter: "replay"` and `modelId: "synthetic-script"`, which is precisely what
 * happened and precisely what BRIEF section 10 requires be recorded.
 *
 * The transcript is held in memory and never committed: the committed prompt/tool-schema regression
 * detector is `corebank-member-lookup.synthetic.transcript.json`, and a second copy of that
 * mechanism would be a second thing to keep in step for no additional signal.
 */
export async function recordedRun(corpus: CorebankWebCorpus): Promise<DiscoveryRun> {
  checkRefs(corpus);
  const recorder = createRecordingModel(
    createScriptedModel(SCRIPT, { modelId: "synthetic-script" }),
    {
      nowMs: frozenClockMs(),
      recordedAt: null,
      synthetic: true,
      note:
        "SYNTHETIC. The assistant turns were authored by hand in " +
        "packages/discovery/test/fixtures/corebank-web.ts; no model produced them and no provider " +
        "was called. NOT evidence of a discovery run.",
    },
  );
  await runOver({ surface: surfaceFor(corpus), model: recorder });
  return runOver({ surface: surfaceFor(corpus), model: createReplayModel(recorder.transcript()) });
}

// ---------------------------------------------------------------------------------------------
// Synthesis
// ---------------------------------------------------------------------------------------------

/** Everything a PERSON owns rather than derives: the capability's name, its routing prose, and
 *  which vendor product this program is written against. SPEC section 2.3 - synthesis will not
 *  generate `whenToUse`, because a generated routing line is a generated routing decision. */
export function synthesisInput(run: DiscoveryRun, corpus: CorebankWebCorpus): SynthesizeInput {
  return {
    run,
    capability: {
      name: "corebank.member.read_share_position",
      title: "Read a member's share position",
      summary:
        "Looks a member up by member number and reports their name, share balance and membership " +
        "status, leaving the servicing session on that member's record.",
      whenToUse: [
        "The member is asking what their share or savings balance is.",
        "A teller needs the member's current position before servicing the account.",
      ],
      whenNotToUse: [
        "You do not have a member number. Identify the member first; this capability will not search by name.",
        "The member is asking about a loan, certificate or card balance - this reads share accounts only.",
      ],
    },
    vendor: {
      product: "CoreBank Servicing",
      productVersionRange: ">=8.0 <9.0",
      sessionProfile: "corebank-teller",
    },
    capabilities: corpus.capabilities,
    tenantId: "riverbend",
    appInstanceId: "riverbend-corebank-01",
    runId: "run:corebank-web-synthesis",
    recordedAt: FROZEN_NOW,
    promptVersion: "discovery/1",
    transcriptRef: null,
  };
}

/** The whole discovery half of SPEC section 1.1, hermetically: no browser, no clock, no key. */
export async function synthesizeFromCorpus(
  corpus: CorebankWebCorpus = loadCorpus(),
): Promise<SynthesisResult> {
  return synthesizeCapability(synthesisInput(await recordedRun(corpus), corpus));
}

/**
 * The exact bytes of `corebank-web.capability.json`, as a function of the committed corpus.
 *
 * One function, called by the emit script AND by the drift test, so the test pins the pipeline the
 * script runs rather than its own second copy of it. If these were two code paths the test could go
 * green over a document nobody would ever regenerate.
 */
export async function emittedBytes(dir: string = HERE): Promise<string> {
  const corpus = loadCorpus(dir);
  const { contract, artifact, report } = await synthesizeFromCorpus(corpus);
  const document: EmittedCapability = {
    _readme: [
      "SYNTHESIZED, NOT HAND-AUTHORED, AND NOT EVIDENCE. @crr/discovery emitted this from a",
      `discovery run over ${OBSERVATIONS_FILE} - a corpus of real Observations captured from`,
      "fixtures/corebank-web through @crr/surface-browser. The model's turns were hand-authored",
      "(no provider was called, no token was spent), so this is NOT evidence of a discovery run;",
      "see evidence/discovery-live/PENDING.md for what would be. It exists so that",
      "packages/runtime/test/synthesized-replay.test.ts can read a SYNTHESIZED artifact back as",
      "data and execute it against the real application - the discovery -> replay seam of",
      "SPEC section 1.1. Regenerate with: pnpm -F @crr/discovery fixtures:synthesized",
    ].join(" "),
    provenance: {
      emittedBy: "packages/discovery/test/fixtures/emit-corebank-web.ts",
      command: "pnpm -F @crr/discovery fixtures:synthesized",
      corpus: OBSERVATIONS_FILE,
      adapter: artifact.provenance.model.adapter,
      modelId: artifact.provenance.model.modelId,
      synthetic: true,
    },
    capabilities: corpus.capabilities,
    contract,
    artifact,
    report,
  };
  // Pretty-printed, unlike the observation corpus, and for the opposite reason: this one is meant
  // to be READ. It is the document a security reviewer would review and an approver would sign
  // over, and a reviewable artifact that arrives as one 40 KB line is reviewable in theory only.
  return `${JSON.stringify(document, null, 2)}\n`;
}
