// `pnpm codegen` - the contract, as types a caller's compiler can hold to.
//
// WHAT THIS BUYS, precisely. `ReplayOutcomeArm<C>` distributes over `C["outcomes"]`, so when `C` is
// a LITERAL type the caller's `switch (r.outcome)` is exhaustive and adding an `OutcomeDecl` to the
// contract is a compile error at every existing call site. That is correct: a new possible answer
// IS a breaking change for a caller. But it only holds while `C` is literal. Hand a caller
// `CapabilityContract` - whose `outcomes` is `readonly OutcomeDecl[]` - and `O["code"]` widens to
// `string`, the switch silently decays into a string comparison, and the mechanism is gone with no
// diagnostic anywhere. So the generated file exists to keep `C` literal, and the runtime digest pin
// exists because a generated file can also be STALE, which no amount of literal typing detects.
//
// WHY A `.ts` AND NOT A `.d.ts`, which is what SPEC section 2.6 says. A `.d.ts` cannot carry a
// runtime value, and `Invocation.capability.contractDigest` is a runtime value: the pin has to
// travel on the wire to be compared against the contract the host loaded. Emitting a declaration
// file would give the caller literal types and then leave it to hand-copy the digest beside them -
// which is precisely the drift the pin exists to catch, reintroduced one layer down. So the emitted
// module is a `.ts` exporting the contract `as const` plus `CONTRACT_DIGEST`, and `tsc` produces the
// `.d.ts` from it. The caller gets both halves and neither can be stale without the other.
//
// THE OUTPUT IS DETERMINISTIC. Same contract in, byte-identical file out, because the file is
// checked in and a codegen step that reorders keys makes every regeneration a diff nobody reads.
// Key order follows the contract schema's own declaration order rather than the input document's,
// so a re-serialised contract cannot change the emitted bytes either.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CapabilityContract, OutcomeDecl } from "@crr/core";

/** What one contract compiles to. `path` is relative to the output directory. */
export interface GeneratedModule {
  readonly path: string;
  readonly source: string;
}

const BANNER = [
  "// GENERATED BY `pnpm codegen`. DO NOT EDIT.",
  "//",
  "// Regenerate after any contract change. The `CONTRACT_DIGEST` below travels on every invocation",
  "// and is compared against the contract the host loaded: if this file is stale the run comes back",
  "// `failed / contract-stale` before a session is brokered, rather than handing this caller an",
  "// outcome its `switch` has never heard of.",
  "",
  "",
].join("\n");

/** `corebank.member.read_share_position` -> `corebank-member-read_share_position.ts` is ugly; the
 *  dots become path-safe underscores and the file keeps the capability's own spelling otherwise. */
export function moduleFileNameOf(capabilityName: string): string {
  return `${capabilityName.replace(/\./g, "__")}.ts`;
}

/** `corebank.member.read_share_position` -> `corebankMemberReadSharePosition`. */
export function identifierOf(capabilityName: string): string {
  const parts = capabilityName.split(/[._-]/).filter((p) => p.length > 0);
  const [head, ...tail] = parts;
  if (head === undefined) throw new Error(`${capabilityName} has no identifier form`);
  return head + tail.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

function pascalOf(capabilityName: string): string {
  const id = identifierOf(capabilityName);
  return id.charAt(0).toUpperCase() + id.slice(1);
}

// ---------------------------------------------------------------------------------------------
// The emitter
// ---------------------------------------------------------------------------------------------

/**
 * One contract, as a TypeScript module.
 *
 * The contract is emitted as a literal with three assertion sites - `name`, `version`, `digest` -
 * because those three are BRANDED types in `@crr/core` and a bare string literal does not inhabit a
 * brand. Everything else is emitted as a plain literal so `as const` gives it a literal type, which
 * is the entire point: `outcomes[n].code` must be `"MEMBER_NOT_FOUND"` and not `string`.
 *
 * `satisfies CapabilityContract` is the assertion that the emitted literal is a real contract. It
 * checks assignability WITHOUT widening the literal, which `: CapabilityContract` would do - and a
 * widened annotation here would silently undo the whole mechanism while still compiling.
 */
export function generateContractModule(contract: CapabilityContract): GeneratedModule {
  const id = identifierOf(contract.name);
  const Pascal = pascalOf(contract.name);
  const body = literal(contract, 0);

  const source = `${BANNER}import type {
  ArgsOf,
  CapabilityContract,
  CapabilityName,
  ContractVersion,
  Digest,
  Invocation,
  OutputsOf,
  ReplayResult,
  WithApproval,
} from "@crr/core";

export const ${id} = ${body} as const satisfies CapabilityContract;

export type ${Pascal} = typeof ${id};

/** The pin. Travels on every invocation; a mismatch is \`failed / contract-stale\`. */
export const CONTRACT_DIGEST = ${JSON.stringify(contract.digest)} as Digest;

/** Spread into an \`Invocation\` so the three identity fields cannot be typed by hand. */
export const CAPABILITY = {
  name: ${JSON.stringify(contract.name)} as CapabilityName,
  version: ${JSON.stringify(contract.version)} as ContractVersion,
  contractDigest: CONTRACT_DIGEST,
} as const;

export type ${Pascal}Args = ArgsOf<${Pascal}>;
export type ${Pascal}Outputs = OutputsOf<${Pascal}>;
/** Four arms. \`switch (r.status)\`, then \`switch (r.outcome)\` - both exhaustive. */
export type ${Pascal}Result = ReplayResult<${Pascal}>;
export type ${Pascal}Invocation = Invocation<${Pascal}>;
/** The approval token is required BY THE TYPE when the capability is irreversible. */
export type ${Pascal}Call = WithApproval<${Pascal}>;

/** Every declared business outcome. An outcome is an ANSWER, not an error. */
export type ${Pascal}Outcome = ${outcomeUnion(contract.outcomes)};
`;

  return { path: moduleFileNameOf(contract.name), source };
}

function outcomeUnion(outcomes: readonly OutcomeDecl[]): string {
  if (outcomes.length === 0) return "never";
  return outcomes.map((o) => JSON.stringify(o.code)).join(" | ");
}

/**
 * A value as TypeScript source.
 *
 * Object keys are emitted in the order the source document holds them, which for a document that
 * came through `parseContract` is the schema's declaration order rather than whatever the JSON file
 * happened to use - zod's `strictObject` rebuilds the object key by key. That is what makes the
 * output deterministic across a re-serialised input.
 */
function literal(value: unknown, depth: number, key?: string): string {
  const pad = "  ".repeat(depth + 1);
  const closePad = "  ".repeat(depth);

  if (value === null) return "null";
  if (typeof value === "string") {
    const text = JSON.stringify(value);
    // Depth 1 is a TOP-LEVEL property of the contract, and only there. A `name` inside a
    // `FieldSpec` or a table column is a plain string; branding one would not compile, and a
    // brand table keyed by name alone would try.
    //
    // The assertion is to the INTERSECTION of the brand and the literal, not to the brand alone.
    // `"mock.member.find" as CapabilityName` type-checks and quietly widens the property to
    // `CapabilityName`, which throws away the literal this whole file exists to preserve -
    // `Invocation<C>["capability"]["name"]` is `C["name"]`, and a caller should not be able to
    // invoke one capability with another's identity because the type said `string`.
    const brand = depth === 1 && key !== undefined ? BRANDS[key] : undefined;
    return brand === undefined ? text : `${text} as ${brand} & ${text}`;
  }
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((item) => `${pad}${literal(item, depth + 1)}`);
    return `[\n${items.join(",\n")},\n${closePad}]`;
  }

  const entries = Object.entries(value as Record<string, unknown>).filter(
    ([, v]) => v !== undefined,
  );
  if (entries.length === 0) return "{}";
  const lines = entries.map(([k, v]) => `${pad}${propertyKey(k)}: ${literal(v, depth + 1, k)}`);
  return `{\n${lines.join(",\n")},\n${closePad}}`;
}

/** The three branded string fields on a contract. */
const BRANDS: Readonly<Record<string, string>> = {
  name: "CapabilityName",
  version: "ContractVersion",
  digest: "Digest",
};

function propertyKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

// ---------------------------------------------------------------------------------------------
// The barrel
// ---------------------------------------------------------------------------------------------

/** One import site for a caller that holds several capabilities. */
export function generateIndexModule(contracts: readonly CapabilityContract[]): GeneratedModule {
  const lines = [BANNER];
  for (const contract of [...contracts].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(
      `export * as ${identifierOf(contract.name)} from "./${moduleFileNameOf(contract.name).replace(/\.ts$/, ".js")}";`,
    );
  }
  return { path: "index.ts", source: `${lines.join("\n")}\n` };
}

// ---------------------------------------------------------------------------------------------
// The writer
// ---------------------------------------------------------------------------------------------

export interface CodegenResult {
  readonly outDir: string;
  readonly written: readonly string[];
  /** Files whose content already matched. `pnpm codegen --check` reports drift from this. */
  readonly unchanged: readonly string[];
}

/**
 * Write the generated modules.
 *
 * Rewriting a file whose bytes already match is avoided on purpose: a codegen step that touches
 * every file on every run makes `git status` useless and makes a build cache miss on nothing.
 */
export function writeGenerated(
  contracts: readonly CapabilityContract[],
  outDir: string,
): CodegenResult {
  mkdirSync(outDir, { recursive: true });
  const modules = [...contracts.map(generateContractModule), generateIndexModule(contracts)];
  const written: string[] = [];
  const unchanged: string[] = [];
  for (const module of modules) {
    const path = join(outDir, module.path);
    if (sameContent(path, module.source)) {
      unchanged.push(module.path);
      continue;
    }
    writeFileSync(path, module.source);
    written.push(module.path);
  }
  return { outDir, written, unchanged };
}

function sameContent(path: string, source: string): boolean {
  try {
    return readFileSync(path, "utf8") === source;
  } catch {
    return false;
  }
}
