import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_MUTANTS } from "../../src/engines/mutants.js";
import { buildKillMatrix, formatKillMatrix } from "../../src/run.js";
import { TERMINAL_SCENARIOS } from "../terminal/scenarios.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../../../..");
const OUT = join(REPO, "evidence/terminal-survivors");

const KILLED_BY_THE_GREEN_SCREEN: Readonly<Record<string, string>> = {
  firstMatch:
    "T13: the name says Search and the ordinal says Exit, so a fallback ranking would press either Enter or F3.",
  countQuorum:
    "T14: a grid field's accessible name is derived from its prompt, so role-name and label-anchored are one piece of evidence.",
  checkpointFirst:
    "T03/T04: the status band carries the business outcome while the screen is still the inquiry screen.",
  noDelta:
    "T08: a repaint that never arrived leaves the previous screen in place, and the checkpoint alone cannot notice that no effect occurred.",
  nearestMatch:
    "T06/T08: a torn read and a stale screen both share words with declared outcome codes, so nearest-string matching invents an answer.",
};

const OUT_OF_REACH: Readonly<Record<string, string>> = {
  noAssert:
    "Needs a target that resolves correctly and is still the wrong thing. This TUI fixture has account rows keyed by suffix and each row belongs to the member it just looked up, so the assert-failed shape is not observable here.",
  noSettleGate:
    "Observationally indistinguishable on this terminal surface. The readiness signal is silence; the measured torn repaint is also silent, so the driver reports settled true even on a half-painted frame. The checkpoint, not the settle flag, is the enforceable gate here.",
  noContinuity:
    "Needs the application to land on a different member's record. This fixture echoes back the account number it was given; producing the divergence would require a fixture that lies about which member it opened.",
  noProvenance:
    "Needs the same validation banner over a caller argument and over an artifact literal. This TUI flow fills one caller-supplied field, so those two provenance rows collapse into one observable case.",
};

function writeText(path: string, body: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
}

function writeJson(path: string, value: unknown): void {
  writeText(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function main(): Promise<void> {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const matrix = await buildKillMatrix(ALL_MUTANTS, TERMINAL_SCENARIOS);
  const killed = matrix.rows
    .filter((row) => row.killedBy.length > 0)
    .map((row) => row.mutant)
    .sort();
  const survivors = matrix.survivors.slice().sort();
  const expectedKilled = Object.keys(KILLED_BY_THE_GREEN_SCREEN).sort();
  const expectedSurvivors = Object.keys(OUT_OF_REACH).sort();
  if (JSON.stringify(killed) !== JSON.stringify(expectedKilled)) {
    throw new Error(`terminal killed set changed: ${killed.join(", ")}`);
  }
  if (JSON.stringify(survivors) !== JSON.stringify(expectedSurvivors)) {
    throw new Error(`terminal survivor set changed: ${survivors.join(", ")}`);
  }
  if (matrix.rows.length !== ALL_MUTANTS.length) {
    throw new Error(`terminal matrix dropped mutants: ${matrix.rows.length}/${ALL_MUTANTS.length}`);
  }

  writeJson(join(OUT, "matrix.json"), {
    scenarioCount: matrix.scenarioIds.length,
    mutantCount: matrix.rows.length,
    killedByTerminal: KILLED_BY_THE_GREEN_SCREEN,
    outOfReachOnTerminal: OUT_OF_REACH,
    matrix,
  });
  writeText(join(OUT, "matrix.txt"), `${formatKillMatrix(matrix)}\n`);
  writeText(
    join(OUT, "README.md"),
    [
      "# terminal survivor matrix",
      "",
      "Generated by `pnpm -F @crr/conformance exec tsx test/evidence/terminal-survivors.ts`.",
      "",
      "This exhibit runs the live green-screen corpus against the same nine mutant engines used by",
      "the browser corpus. It intentionally preserves four survivors because the terminal surface",
      "does not expose an observation that distinguishes those defects from the reference engine.",
      "",
      "`matrix.json` records both categories: mutants killed by terminal-native facts, and mutants",
      "out of reach for this fixture/surface. The script fails if either list changes without the",
      "evidence being regenerated.",
      "",
    ].join("\n"),
  );
  process.stdout.write(
    `terminal survivor evidence: ${matrix.scenarioIds.length} scenarios, ${matrix.survivors.length} documented survivors\n`,
  );
}

await main();
